apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::022433421129:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-10V472W1VSR83
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::022433421129:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-26T08:26:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1708"
  uid: fb0a34cb-eb32-46a9-8dbc-b6eb4cc25ea3
